---
contentdir: "content"
layoutdir: "layouts"
publishdir: "public"
indexes:
  category: "categories"
baseurl: "http://arthur-c.github.io/"
title: "Arthur's Pages"
canonifyurls: false
theme: "hyde"
params:
  description: "clement.arthur@gmail.com"
  author: "Arthur Clément"
  github: "https://github.com/arthur-c"
  disqusShortname: "arthurc"
...


